worker_processes 1;
error_log /dev/stderr warn;
pid /run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    access_log off;
    server {
        listen 443 ssl;
        server_name applynow.hdfc.bank.in;

        ssl_certificate     /etc/tls/fullchain.pem;
        ssl_certificate_key /etc/tls/privkey.pem;
        ssl_protocols       TLSv1.2 TLSv1.3;

        location / {
            # If the client requests a WebSocket upgrade, proxy to wsproxy
            if ($http_upgrade = "websocket") {
                proxy_pass http://127.0.0.1:8080;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
                break;
            }
            # Render health check (plain HTTP GET) receives 200 OK
            return 200 "OK";
            add_header Content-Type text/plain;
        }
    }
}
